export const MINIMAL_UNIT_FACTOR = 100;

export const LONG_RENT_PERIOD_MIN_COST = 1 * MINIMAL_UNIT_FACTOR;
export const SHORT_RENT_PERIOD_MIN_COST = 1 * MINIMAL_UNIT_FACTOR;
export const LONG_RENT_PERIOD_MAX_COST = 9999999999999 * MINIMAL_UNIT_FACTOR; // 9 999 999 999 999
export const SHORT_RENT_PERIOD_MAX_COST = 9999999999999 * MINIMAL_UNIT_FACTOR; // 9 999 999 999 999

export const SHORT_RENT_PARTIAL_ALLOWED_DAYS_BEFORE_ARRIVAL = 30;

export const LONG_TERM_RENT_ARRIVAL_TIME = '14:00'; // hardcode, use in send-contract-offer.service.ts
export const LONG_TERM_RENT_DEPARTURE_TIME = '12:00'; // hardcode, use in send-contract-offer.service.ts

export const LIVIN_SHORT_TERM_RENT_SENDER_TAX_RATE = 0.12;
export const LIVIN_SHORT_TERM_RENT_RECIPIENT_TAX_RATE = 0.03;

export const LIVIN_LONG_TERM_RENT_SENDER_TAX_RATE = 0.08;
export const LIVIN_LONG_TERM_RENT_RECIPIENT_TAX_RATE = 0.0;

export const INNOPAY_CASH_IN_TAX_RATE = 0.027;
export const INNOPAY_CASH_OUT_TAX_RATE = 0.013;

export const PAYMENT_LIVIN_SENDER_NAME = 'LIVIN';

export const FINE_RATE = 0.2;
