FROM node:16-alpine3.15 AS builder
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:16-alpine3.15 AS runner
WORKDIR /app
COPY --from=builder /app ./
RUN apk add bash
EXPOSE 5000
ENTRYPOINT ["sh", "-c"]
CMD ["yarn staging:migration:latest && yarn staging:seed:run && node -r ./tsconfig-paths-bootstrap.js dist/src/main.js"]